### PR TITLE
`run.sh` bug fixing and wrapping into zsh plugin

### PR DESCRIPTION
**Pull request by lainiwa**
List of changes I made:

- Make `run.sh` correctly run when called from other directory rather then repo's root.
- User now choose among not all directories, but only those containing `.zshrc` in them. The search is now recursive, so a user can have multiple configurations in her directory. To demonstrate that, I made 2 copies of my configs in their own sub-directories.
- Wrap the repo into zsh plugin.
- Include installation of `zplugin` into `Dockerfile`. Thus the script no more relies on the installation being embedded into the config. Config of NICHOLAS85 now also works (*somewhat*. as it assumes presence of golang and some specific tools in the system).

Not sure if anything else could be done here. It seems to work on the very few examples we have in the repo...

### CODE REVIEW

**Comment by psprint** [comment]
Thanks. I wonder about the install instruction for fzf-bin. It should contain `from'gh-r' as"command"`, no? Also, I've ran your 1st config and to my surprise zplugin's completion isn't working. I must dive into the cause.

**Comment by psprint** [comment]
PS. I've updated the commands in the README :)

**Comment by lainiwa** [comment]
Indeed, I lost the `zplugin ice` command before loading fzf. By the way, it works without the `as"command"` part, too.

Also: It seems that the conditional copy command you introduced doesn't work as expected. It fails when there is no `zshrc.zsh`:
```sh
Step 9/11 : COPY --chown=user lainiwa/1st_config/zshrc.zsh* /home/user/.zshrc
COPY failed: no source files were specified
```

 I think this task could be done by copying all files to the docker user's `$HOME` (as it already does) and then having a `RUN` directive with a conditional `mv` or a `mv ... || true`.

**Comment by lainiwa** [comment]
Although for me it feels like it might be a better way to just encourage folks to name their configs `.zshrc` if they want it to be loadable, and naming them otherwise if not. It would be a clear distinction, and we would not have to go guessing every possible name a "full" config might have.

**Comment by psprint** [comment]
I think that there should be one naming scheme without leading-dot to allow users to make their zshrc easily visible after cloning and still runnable. I've changed the `COPY` directive to `RUN cp …` so it doesn't cause any problems. I think that I'll merge the branch into master now.

**Pull request merged**
